apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
  labels:
    app: reddit-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit-clone
        # CHANGE: We use a placeholder string that Jenkins will replace
        image: DOCKER_IMAGE_PLACEHOLDER 
        # CHANGE: Force K8s to pull the image even if it exists locally
        imagePullPolicy: Always
        ports:
        - containerPort: 3000